[package]
name = "pocket-persona"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Persona-compatible native VRM desktop character proof of concept"

[dependencies]
pocket3d = { workspace = true }
pocket-mod = { workspace = true }
pocket-vrm = { workspace = true }
pocket-widget = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
glam = { workspace = true, features = ["std"] }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
